final project
w4xxwrld/full-stack-dev pull request #11
Opened 2024-12-10 19:19 UTC by w4xxwrld

what was done:
1. created postman collection
2. code tested on digital ocean server on api.shakhnazar.online
3. endpoints tested on postman(see loom video in skool)

2024-12-10 19:29 UTC, aissayev requested changes

2024-12-10 19:29 UTC, aissayev commented on back-end-102/final-project/src/main.py
> +SECRET_KEY = "BaVArIanMotORWorKs3PoInT5LIterTwINTUrBo"
ideally should get the secret key from `.env` file, so it is not exposed in the repo

2024-12-10 19:29 UTC, aissayev commented on back-end-102/final-project/src/main.py
> +SECRET_KEY = "BaVArIanMotORWorKs3PoInT5LIterTwINTUrBo"
.env should be gitignored

2024-12-10 19:29 UTC, aissayev commented on back-end-102/final-project/src/main.py
> +    project_id: int
Put classes into a separate file and import it

2024-12-11 08:25 UTC, w4xxwrld commented
https://www.loom.com/share/d0c5d664b5e54ef9bfb0a67421b43068
here's the video with demonstration of fixes and file moves.
commit with all the changes pushed

2024-12-11 08:25 UTC, merged

2024-12-11 15:24 UTC, aissayev reviewed
lgtm